Adding missing const qualifier.
Addressing
mod_intercept_form_submit.c: In function 'intercept_form_submit_process_buffer':
mod_intercept_form_submit.c:210:22: error: initialization discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  210 |         char * sep = memchr(buffer, '=', buffer_length);
      |                      ^~~~~~
cc1: all warnings being treated as errors
apxs:Error: Command failed with rc=65536